/* generated by Hamber vX.Y.Z */
import { HamberComponent, init, safe_not_equal } from "hamber/internal";

import { onMount } from 'hamber';

function instance($$self, $$props, $$invalidate) {
	let { foo = 'bar' } = $$props;

	onMount(() => {
		alert(JSON.stringify(data()));
	});

	$$self.$$set = $$props => {
		if ('foo' in $$props) $$invalidate(0, foo = $$props.foo);
	};

	return [foo];
}

class Component extends HamberComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, { foo: 0 });
	}
}

export default Component;
