/* generated by Hamber vX.Y.Z */
import {
	HamberComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "hamber/internal";

function create_fragment(ctx) {
	let b;

	return {
		c() {
			b = element("b");
			b.textContent = `${get_answer()}`;
		},
		m(target, anchor) {
			insert(target, b, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(b);
		}
	};
}

const ANSWER = 42;

function get_answer() {
	return ANSWER;
}

class Component extends HamberComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
