/* generated by Hamber vX.Y.Z */
import {
	HamberComponent,
	action_destroyer,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "hamber/internal";

function create_fragment(ctx) {
	let a;
	let link_action;
	let mounted;
	let dispose;

	return {
		c() {
			a = element("a");
			a.textContent = "Test";
			attr(a, "href", "#");
		},
		m(target, anchor) {
			insert(target, a, anchor);

			if (!mounted) {
				dispose = action_destroyer(link_action = link.call(null, a));
				mounted = true;
			}
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(a);
			mounted = false;
			dispose();
		}
	};
}

function link(node) {
	function onClick(event) {
		event.preventDefault();
		history.pushState(null, null, event.target.href);
	}

	node.addEventListener('click', onClick);

	return {
		destroy() {
			node.removeEventListener('click', onClick);
		}
	};
}

class Component extends HamberComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
