/* generated by Hamber vX.Y.Z */
import { HamberComponent, init, safe_not_equal } from "hamber/internal";

function instance($$self) {
	const a = 1 + 2;
	return [];
}

class Component extends HamberComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, {});
	}
}

export default Component;
