/* generated by Hamber vX.Y.Z */
import {
	HamberComponent,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "hamber/internal";

function create_fragment(ctx) {
	let a;

	return {
		c() {
			a = element("a");
			a.innerHTML = `<span class="inner"></span>`;
			attr(a, "class", "outer");
		},
		m(target, anchor) {
			insert(target, a, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(a);
		}
	};
}

class Component extends HamberComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
